services:
  auth-service:
    image: skeet15/auth-vivelibre:latest
    ports:
      - "8080:8080"

  token-service:
    build: ./exercise-2-token-service
    image: token-service:latest
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - auth-service
